name:                web
version:             0.1.0.0
github:              "penguinshunya/haskell-web-application"
license:             BSD3
author:              "penguinshunya"
maintainer:          "penguinshunya@hotmail.com"
copyright:           "2018 penguinshunya"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/penguinshunya/haskell-web-application#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web
    - warp
    - wai
    - http-types

tests:
  web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web
